from __future__ import annotations
from dataclasses import dataclass
@dataclass(frozen=True,slots=True)
class DBQField:
 key:str;label:str;section:str;required:bool=False;kind:str="user";guidance:str=""
@dataclass(frozen=True,slots=True)
class DBQTemplate:
 template_id:str;name:str;fields:tuple[DBQField,...]
BASE=(DBQField("claimant_reported_symptoms","Claimant-reported symptoms","History",True,"claimant"),DBQField("diagnoses","Diagnoses","Diagnosis",True,"documented"),DBQField("medical_history","Medical history","History",True,"documented"),DBQField("treatment_history","Treatment history","History",False,"documented"),DBQField("medications","Medications","History",False,"documented"),DBQField("diagnostic_testing_imaging","Diagnostic testing and imaging","Testing",False,"documented"),DBQField("functional_impact","Functional impact","Impact",True,"claimant"),DBQField("flare_ups","Flare-ups","Impact",False,"claimant"),DBQField("repeated_use_limitations","Repeated-use limitations","Impact",False,"claimant"),DBQField("occupational_impact","Occupational impact","Impact",False,"claimant"),DBQField("activities_daily_living","Activities of daily living impact","Impact",False,"claimant"),DBQField("assistive_devices","Assistive devices","Impact",False,"documented"),DBQField("objective_findings","Objective findings","Examination",True,"examiner","Requires direct examination or provider documentation."),DBQField("remarks","Remarks","Remarks",False,"user"))
SPECS={
"general_medical":("General Medical",()),"mental_disorders":("Mental Disorders",(DBQField("occupational_social_impairment","Occupational and social impairment","Examination",True,"examiner"),)),"headaches_migraines":("Headaches/Migraines",(DBQField("headache_frequency","Headache frequency","History",True,"claimant"),DBQField("prostrating_attacks","Prostrating attacks","Examination",True,"examiner"))),"back_thoracolumbar":("Back/Thoracolumbar Spine",(DBQField("range_of_motion","Range of motion","Examination",True,"examiner","Must be measured by an examiner."),)),"neck_cervical":("Neck/Cervical Spine",(DBQField("range_of_motion","Range of motion","Examination",True,"examiner"),)),"knee_lower_leg":("Knee and Lower Leg",(DBQField("range_of_motion","Range of motion","Examination",True,"examiner"),DBQField("joint_stability","Joint stability testing","Examination",True,"examiner"))),"shoulder_arm":("Shoulder and Arm",(DBQField("range_of_motion","Range of motion","Examination",True,"examiner"),)),"hearing_tinnitus":("Hearing Loss and Tinnitus",(DBQField("audiometric_results","Audiometric results","Testing",True,"examiner"),)),"sinusitis_rhinitis":("Sinusitis/Rhinitis",(DBQField("episodes_frequency","Episode frequency","History",True,"claimant"),)),"sleep_apnea":("Sleep Apnea",(DBQField("sleep_study","Sleep study","Testing",True,"documented"),)),"male_reproductive":("Male Reproductive Organ Conditions",(DBQField("physical_examination","Physical examination","Examination",True,"examiner"),)),"urinary_voiding":("Urinary Tract/Voiding Dysfunction",(DBQField("voiding_frequency","Voiding frequency","History",True,"claimant"),)),"intestinal_ibs":("Intestinal Conditions/IBS",(DBQField("episodes_frequency","Episode frequency","History",True,"claimant"),)),"temporomandibular":("Temporomandibular Disorders",(DBQField("interincisal_range","Interincisal range","Examination",True,"examiner"),)),}
TEMPLATES={k:DBQTemplate(k,n,BASE+tuple(extra)) for k,(n,extra) in SPECS.items()}
def get_template(template_id):
 try:return TEMPLATES[template_id]
 except KeyError:raise ValueError(f"Unsupported DBQ template: {template_id}") from None
def list_templates():return tuple(TEMPLATES.values())
